// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCdcWlhgdsSt1ERFmWCLu1Eqq4InP7C9g',
    appId: '1:406078744191:web:60969b1986e0dcb17b814a',
    messagingSenderId: '406078744191',
    projectId: 'dearly-8e394',
    authDomain: 'dearly-8e394.firebaseapp.com',
    storageBucket: 'dearly-8e394.firebasestorage.app',
    measurementId: 'G-4BTG41MWDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvqeVLhMbjpEw9S800qMtz9JHCxSgZXnc',
    appId: '1:406078744191:android:08f381296be8f73d7b814a',
    messagingSenderId: '406078744191',
    projectId: 'dearly-8e394',
    storageBucket: 'dearly-8e394.firebasestorage.app',
  );

}